# Generated by Django 4.2.3 on 2023-07-21 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='restaurant',
        #     name='image',
        #     field=models.CharField(default=None, max_length=500, null=True),
        # ),
        # migrations.AddField(
        #     model_name='restaurant',
        #     name='password',
        #     field=models.CharField(default=None, max_length=20, null=True),
        # ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        # migrations.CreateModel(
        #     name='Review',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('point', models.IntegerField()),
        #         ('comment', models.CharField(max_length=500)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third.restaurant')),
        #     ],
        # ),
    ]
